### PR TITLE
python3-compatibilty: spooler/python/plugins/disclaimer.py:

### PR DESCRIPTION
**Pull request by umgfoin**
python3-compatibilty: replace unicode(str) by .decode('utf-8').
Maybe a 'strict'-attribute might be desired, too.

### CODE REVIEW

**Comment by longsleep** [comment]
Thanks - there is a fix for this in our patch queue already - we hope to have all py3 issues with scripts like this fixed up with 8.7.1.

**Comment by umgfoin** [comment]
@longsleep 
Very good - there's also another issue with type(long) in pluginmanager.py.
General question: Is the goal for 8.7.1 py3.x + backward-compatibility or can we switch to py3.x only code.

**Comment by longsleep** [comment]
> Very good - there's also another issue with type(long) in pluginmanager.py.
Yes.

> General question: Is the goal for 8.7.1 py3.x + backward-compatibility or can we switch to py3.x only code.

For 8.7 Python 2 is used on some (older) supported distributions, thus Python 2 compatibility is required for all changes (with a few exceptions like the new REST API which is Python 3 only and not available on those older distros).

**Comment by longsleep** [comment]
Fixed by c6d973a7e9d6745ddcf02925c8c008dc2fb4bae3 in kc-8.7.x branch

**Pull request closed without merging**
