### PR TITLE
Fix broken init-scripts for search, presence and spamd (introduced by commit 5ec95b5cabf)

### PR DESCRIPTION
**Pull request by umgfoin**

### CODE REVIEW

**Comment by fbartels** [comment]
Hi @umgfoin,

thanks a lot for your pr. We have cherry picked your commit and opened an internal pr for it.

Just for reference internal pr is https://stash.kopano.io/projects/KC/repos/kopanocore/pull-requests/2544/overview.

We are actually currently discussing to remove the init scripts from the source altogether and focus more on leveraging systemd for starting up our services.

**Comment by tijuca** [comment]
Why not simply keep them? They normally need no maintenance at all and of course not all user will use Systemd. And as long people give feedback if something needs some polish all is fine.

**Comment by longsleep** [comment]
> Why not simply keep them? They normally need no maintenance at all and of course not all user will use Systemd. And as long people give feedback if something needs some polish all is fine.

We are currently discussing if and how we can rely on features provided by modern service runners. Especially related to sandboxing, namespaces, dropping of caps. Possible service runners would be systemd and container runtimes like docker. This might mean that it becomes feasible that some of the daemon support, dedicated logging stuff, user switching and similar system level features could go away from the code base as soon as they come from the service infrastructure provided by the platform. Since what is currently in master will be eventually 9.0 it is the time to clean up stuff we do no longer support. I hope this gives some insight. Any discussion and arguments why we might want to keep init scripts or even might want to keep minimal compatibility for them are very welcome.

**Comment by fbartels** [comment]
Has been merged in https://github.com/Kopano-dev/kopano-core/commit/1b74d1ba8ed6d39c309e9b4bb17165be57f157e3

**Pull request closed without merging**
