### PR TITLE
Fix SSL setup for Kopano 8.7.x with OpenSSL 1.1.x+

### PR DESCRIPTION
**Pull request by hwundram**
This patch implements conditional new-style SSL setup for Kopano daemons using the
API that OpenSSL 1.1.x exposes, setting minimum/maximum protocol and using a
one-stop initialization function and implicit cleanup. The code tries to keep the
current configuration options for SSL intact (i.e., uses an Apache-style heuristic
to map a set of disabled/enabled protocols to a min/max-range), and does not
introduce additional SSL parameters.

In addition to the OpenSSL initialization changes, this patch also fixes problems
with the ECChannel std::atomic implementation which seems incomplete as it stands
(see commit 9f9a199a6e60d146dbc5ae444f3116650328fad1), and two small semantic
problems with the use of SSL_shutdown/SSL_clear in the initialization routine
for an SSL connection.

### CODE REVIEW

**Comment by jengelh** [comment]
Could you please split this up into multiple commits so it can be better understood.
* one for the return value changes
* one for the `SSL_shutdown` fix
* one for the `SSL_set_accept_state` removal
* one for the change to `lpCTX.exchange`
* and one for the rest (protocol string evaluation).

**Comment by hwundram** [comment]
Patch has been split up into parts; the first is important (to fix SSL in Kopano servers on 8.7.x), all others are optional.

**Comment by hwundram** [comment]
Just as a sidenote: please be aware that the initial patch of the series restores the SSL-functionality of Kopano, but is incomplete in the sense that it is not a proper implementation of atomic accesses to SSL_CTX, which would require locking in HrSetCtx and HrEnableTLS.

Tacking on std::atomic for accesses to the SSL_CTX is not enough to actually make sure that reloading the SSL context while a Kopano server is operating does not lead to spurious segmentation faults due to race conditions (SSL_CTX can be used after being freed, when HrEnableTLS is preemted after getting the lpCTX pointer but before constructing the SSL context, while HrSetCtx is run in parallel). So, don't reload kopano to get new certificate material, always restart it, even with this patch.

I've not fixed this "properly" due to the fact that I gather that the general framework is being reworked, but if there's interest, I'll create a proper PR just for this specific point.

**Comment by jengelh** [comment]
Sure, just send it.

**Comment by jengelh** [comment]
Edited the commit messages a little but left the treeishs as-is. So published in heads/kc-8.7.x.

**Comment by jengelh** [comment]
```
[  146s] ../common/ECChannel.cpp: In static member function 'static HRESULT KC::ECChannel::HrSetCtx(KC::ECConfig*)':
[  146s] ../common/ECChannel.cpp:118:31: error: 'ENGINE_load_builtin_engines' was not declared in this scope
[  146s]    ENGINE_load_builtin_engines();
[  146s]                                ^
[  146s] ../common/ECChannel.cpp:121:32: error: 'OPENSSL_load_builtin_modules' was not declared in this scope
[  146s]    OPENSSL_load_builtin_modules();
[  146s]                                 ^
[  146s] Makefile:4535: recipe for target 'common/ECChannel.lo' failed
[  146s] make[4]: *** [common/ECChannel.lo] Error 1
[  146s] make[4]: *** Waiting for unfinished jobs....
```
on Ubuntu 16.04 (uses openssl-1.0.2g-1ubuntu4).

**Comment by jengelh** [comment]
Just some missing headers, so I'll add those.

**Comment by hwundram** [comment]
> Just some missing headers, so I'll add those.

Interestingly, Debian 9 (which also has OpenSSL 1.0.2g) didn't have these problems building, that's where I tested the pre-OpenSSL-1.1 part of the code. Possibly, my development environment already has those headers included through some other headers. Thanks for the fix!

**Pull request closed without merging**
